--BD- PRACTICA 6, ENRIQUE BALLESTEROS HORCAJO, IGNACIO IKER PRADO RUJAS
--APARTADO 1:
CREATE TABLE REGISTRO_VENTAS ( 
  COD_REST NUMBER(8) PRIMARY KEY REFERENCES Restaurantes, 
  TOTAL_PEDIDOS NUMBER, 
  FECHA_ULT_PEDIDO DATE 
); 

INSERT INTO REGISTRO_VENTAS VALUES (1234, 2, '17/2/09');
INSERT INTO REGISTRO_VENTAS VALUES (2345, 2, '17/2/09');
INSERT INTO REGISTRO_VENTAS VALUES (3456, 3, '16/2/09');
INSERT INTO REGISTRO_VENTAS VALUES (5678, 2, '16/2/09');

--------------------------------------------------------------------------------------------

--APARTADO 2: 

CREATE OR REPLACE 
TRIGGER CONTROL_DETALLE_PEDIDOS
AFTER UPDATE OR DELETE
ON PEDIDOS 
FOR EACH ROW 
DECLARE
  FECHA_ULTIMO_PEDIDO PEDIDOS.FECHA_HORA_ENTREGA%TYPE;
  CURSOR cursorContiene IS 
   SELECT DISTINCT PEDIDO, RESTAURANTE
   FROM CONTIENE;
  cContiene cursorContiene%ROWTYPE;

BEGIN 
IF UPDATING THEN
   FOR cContiene IN cursorContiene LOOP
    IF cContiene.PEDIDO = :OLD.CODIGO THEN 
      SELECT FECHA_ULT_PEDIDO
      INTO FECHA_ULTIMO_PEDIDO
      FROM REGISTRO_VENTAS
      WHERE COD_REST = cContiene.RESTAURANTE;
      IF :NEW.FECHA_HORA_ENTREGA > FECHA_ULTIMO_PEDIDO THEN
        UPDATE REGISTRO_VENTAS
        SET FECHA_ULT_PEDIDO = :NEW.FECHA_HORA_ENTREGA
        WHERE COD_REST = cContiene.RESTAURANTE;
      END IF;
    END IF;
  END LOOP; 
  
ELSIF DELETING THEN 
  FOR cContiene IN cursorContiene LOOP
    IF cContiene.PEDIDO = :OLD.CODIGO THEN 
      UPDATE REGISTRO_VENTAS  
      SET TOTAL_PEDIDOS = TOTAL_PEDIDOS - 1
      WHERE COD_REST = cContiene.RESTAURANTE;
    END IF;
  END LOOP; 
END IF;
END;  
  
--Prueba para el caso de UPDATE
UPDATE PEDIDOS
SET FECHA_HORA_ENTREGA = '20/1/14'
WHERE CODIGO = '1';

--Prueba para el caso de DELETE
DELETE FROM PEDIDOS 
WHERE CODIGO = '2';




